# Generated by Django 4.0.5 on 2022-06-09 20:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to='')),
            ],
        ),
    ]
