# Generated by Django 4.0.5 on 2022-06-09 20:41

from django.db import migrations, models
import mocker.models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0002_alter_uploadedpdf_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='upload_filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='pdf',
            field=models.FileField(upload_to=mocker.models.user_path),
        ),
    ]
