# Generated by Django 4.0.5 on 2022-06-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0003_uploadedpdf_upload_filename_uploadedpdf_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='upload_filename',
            new_name='filename_slug',
        ),
    ]
