# Generated by Django 4.0.5 on 2022-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0004_rename_upload_filename_uploadedpdf_filename_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='is_guest_upload',
            field=models.BooleanField(default=True),
        ),
    ]
