# Generated by Django 4.1 on 2022-08-05 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PDFDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pages', models.PositiveIntegerField(default=0)),
                ('save_path', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_string', models.TextField(default='')),
                ('pdf_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BuildPDF.pdfdoc')),
            ],
        ),
        migrations.CreateModel(
            name='BuildPDFTask',
            fields=[
                ('backgroundtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BuildPDF.backgroundtask')),
                ('pdf_doc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BuildPDF.pdfdoc')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('BuildPDF.backgroundtask',),
        ),
    ]
