# Generated by Django 4.1 on 2022-08-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildPDF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpage',
            name='zero_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildpdftask',
            name='pdf_doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuildPDF.pdfdoc'),
        ),
    ]
