# Generated by Django 4.1 on 2022-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildPDF', '0002_pdfpage_zero_index_alter_buildpdftask_pdf_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HueyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huey_id', models.UUIDField(null=True)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('date_created', models.DateTimeField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
