# Generated by Django 4.1 on 2022-08-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildPDF', '0003_hueyprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundtask',
            old_name='uuid',
            new_name='task_id',
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='huey_process',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuildPDF.hueyprocess'),
        ),
    ]
