# Generated by Django 4.1 on 2022-08-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildPDF', '0004_rename_uuid_backgroundtask_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdoc',
            name='nice_name',
            field=models.TextField(default=''),
        ),
    ]
