# Generated by Django 4.0.6 on 2022-07-30 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HueyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='todo', max_length=16)),
                ('huey_id', models.UUIDField(null=True)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('message', models.TextField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AddTwoNumbersError',
            fields=[
                ('backgroundfunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.backgroundfunction')),
                ('first', models.PositiveIntegerField(null=True)),
                ('second', models.PositiveIntegerField(null=True)),
                ('result', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.backgroundfunction',),
        ),
        migrations.CreateModel(
            name='AddTwoNumbersErrorTask',
            fields=[
                ('hueytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.hueytask')),
                ('first', models.PositiveIntegerField(null=True)),
                ('second', models.PositiveIntegerField(null=True)),
                ('result', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.hueytask',),
        ),
        migrations.CreateModel(
            name='AddTwoNumbersTask',
            fields=[
                ('hueytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.hueytask')),
                ('first', models.PositiveIntegerField(null=True)),
                ('second', models.PositiveIntegerField(null=True)),
                ('result', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.hueytask',),
        ),
        migrations.CreateModel(
            name='RandomNumberGen',
            fields=[
                ('backgroundfunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.backgroundfunction')),
                ('is_even_guess', models.BooleanField(default=False)),
                ('result', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.backgroundfunction',),
        ),
        migrations.CreateModel(
            name='RandomNumberGenTask',
            fields=[
                ('hueytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.hueytask')),
                ('is_even_guess', models.BooleanField(default=False)),
                ('result', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.hueytask',),
        ),
        migrations.CreateModel(
            name='TrainMLModelTask',
            fields=[
                ('hueytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_huey.hueytask')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ml_huey.hueytask',),
        ),
        migrations.CreateModel(
            name='HueyRelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='todo', max_length=16)),
                ('huey_id', models.UUIDField(null=True)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('message', models.TextField(null=True)),
                ('function', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_huey.backgroundfunction')),
            ],
        ),
        migrations.CreateModel(
            name='KNNModelEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_save_path', models.TextField(null=True)),
                ('n_neighbors', models.PositiveIntegerField(null=True)),
                ('train_acc', models.FloatField(null=True)),
                ('test_acc', models.FloatField(null=True)),
                ('train_task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_huey.trainmlmodeltask')),
            ],
        ),
    ]
