# Generated by Django 4.0.6 on 2022-08-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_huey', '0002_backgroundfunction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hueyreltask',
            name='function',
        ),
        migrations.AddField(
            model_name='backgroundfunction',
            name='huey_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_huey.hueyreltask'),
        ),
    ]
